### ISSUE TITLE
Compatibility for globalize >= 5.0

### ISSUE THREAD

**Issue by ouelletv** [scarfacedeb/rails_admin_globalize_field#17] opened 2015-07-13 12:35 UTC
Would be nice :)

**Comment by scarfacedeb** [comment] 2015-07-13 12:43
@ouelletv yeah 😳, I can't find the time to check it out.
Some of the tests are failing with globalize >= 5.0 and it's most likely caused by monkey patching of rails internals.
I'll try to debug it next weekend.

**Comment by chaucerling** [comment] 2015-10-28 04:28
@scarfacedeb Are you free to accept the PR

**Comment by ouelletv** [comment] 2015-10-30 13:36
+1

**Comment by maximski** [comment] 2015-11-12 01:19
+1

**Comment by scarfacedeb** [comment] 2015-11-12 15:12
@maximski @ouelletv @chaucerling I accepted the PR. 
Sorry for the delay. I'm moving to another city at the moment.

**Closed by scarfacedeb** 2015-11-12 15:12 UTC
